### ISSUE TITLE
msg.setUserData exception in JCSMPXMLMessage class - when longer than 36 bytes

### ISSUE THREAD

**Issue by pwoodward-solace** [SolaceLabs/solace-kafka-connector-sink#10]
When topic + kafkaPartition + kafkaOffset is longer than 36 bytes there is an exception.

**Comment by hschaffner** [comment]
In the Sink Connector you create pluggable record processors. In this way you can implement the mapping from the Kafka Record to a Solace messages as a pluggable processor that is loaded at run-time based on the connector configuration file. You can create multiple processors for the connector and just start the connector with the one you want based on the configuration file.
 
For the Simple Record Processor test we added the Kafka Topic, partition and offset information in the Solace User Data header. However, this is not required, it was just a way of having the partition offset to be able to have Kafka replay know where to start from if a relay was necessary. However, in the sample we also duplicate this data where we create a Solace  SDT (Structured Data Type) and add it as user property as well, so the userdata part in the record processor just needs to be commented out.  Big Kafka Topic names push the userdata header over the limit on size.
 
So for the simple record processor, the relevant code is:
 
 
// Add Record Topic,Parition,Offset to Solace Msg in case we need to track offset restart
    String userData = "T:" + record.topic() + ",P:" + record.kafkaPartition() 
        + ",O:" + record.kafkaOffset();
    msg.setUserData(userData.getBytes(StandardCharsets.UTF_8)); 
    
    // Add Record Topic,Partition,Offset to Solace Msg as header properties 
    // in case we need to track offset restart
    SDTMap userHeader = JCSMPFactory.onlyInstance().createMap();
    try {
      userHeader.putString("k_topic", record.topic());
      userHeader.putInteger("k_partition", record.kafkaPartition());
      userHeader.putLong("k_offset", record.kafkaOffset());
    } catch (SDTException e) {
      log.info("Received Solace SDTException {}, with the following: {} ", 
          e.getCause(), e.getStackTrace());
    }
    msg.setProperties(userHeader);
 
 
To fix it, just comment out the unnecessary code from the sample like:
 
 
// Add Record Topic,Parition,Offset to Solace Msg in case we need to track offset restart
    //String userData = "T:" + record.topic() + ",P:" + record.kafkaPartition() 
    //    + ",O:" + record.kafkaOffset();
    //msg.setUserData(userData.getBytes(StandardCharsets.UTF_8)); 
    
    // Add Record Topic,Partition,Offset to Solace Msg as header properties 
    // in case we need to track offset restart
    SDTMap userHeader = JCSMPFactory.onlyInstance().createMap();
    try {
      userHeader.putString("k_topic", record.topic());
      userHeader.putInteger("k_partition", record.kafkaPartition());
      userHeader.putLong("k_offset", record.kafkaOffset());
    } catch (SDTException e) {
      log.info("Received Solace SDTException {}, with the following: {} ", 
          e.getCause(), e.getStackTrace());
    }
    msg.setProperties(userHeader);
 
Now when you run the connector and write a message to the Kafka topic, the sink connector produces a Solace message similar to:
 
^^^^^^^^^^^^^^^^^^ Start Message ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Destination:                            Queue 'testQ'
AppMessageType:                         ResendOfKakfaTopic: xyz.xyz.xyz.org1.org2.for1.for2.SampleTestTopic
SequenceNumber:                         1
SendTimestamp:                          1557451264745 (Thu May 09 2019 21:21:04)
Priority:                               4
Class Of Service:                       USER_COS_1
DeliveryMode:                           PERSISTENT
Message Id:                             1
User Property Map:                      3 entries
  Key 'k_offset' (Long): 0
  Key 'k_topic' (String): xyz.xyz.xyz.org1.org2.for1.for2.SampleTestTopic
  Key 'k_partition' (Integer): 1
 
Binary Attachment:                      len=7
  74 65 73 74 69 6e 67                                  testing
 
 
^^^^^^^^^^^^^^^^^^ End Message ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
 
Hope this helps,
Heinz
